In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('customer.csv')
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [3]:
df=df.iloc[:,2:]

In [4]:
df.sample(5)

,review,education,purchased
17,Poor,UG,Yes
37,Average,PG,Yes
10,Good,UG,Yes
7,Poor,School,Yes
23,Good,School,No


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.3,random_state=42)
X_train.shape,y_train.shape

((35, 2), (35,))

In [6]:
X_train,y_train

(     review education
 6      Good    School
 41     Good        PG
 46     Poor        PG
 47     Good        PG
 15     Poor        UG
 9      Good        UG
 16     Poor        UG
 24  Average        PG
 34  Average    School
 31     Poor    School
 0   Average    School
 44  Average        UG
 27     Poor        PG
 33     Good        PG
 5   Average    School
 29  Average        UG
 11     Good        UG
 36     Good        UG
 1      Poor        UG
 21  Average        PG
 2      Good        PG
 43     Poor        PG
 35     Poor    School
 23     Good    School
 40     Good    School
 10     Good        UG
 22     Poor        PG
 18     Good    School
 49     Good        UG
 20  Average    School
 7      Poor    School
 42     Good        PG
 14     Poor        PG
 28     Poor    School
 38     Good    School,
 6      No
 41    Yes
 46     No
 47    Yes
 15     No
 9     Yes
 16    Yes
 24    Yes
 34     No
 31    Yes
 0      No
 44     No
 27     No
 33    Yes
 5     Yes
 29   

In [7]:

from sklearn.preprocessing import OrdinalEncoder

oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
X_train=oe.fit_transform(X_train)
X_train


array([[2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [8]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [9]:
X_train

array([[2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [10]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [11]:
y_train= le.fit_transform(y_train)
y_test= le.transform(y_test)
y_train

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])